import { Schema, model } from "mongoose";

// the filter_id that will generated by the mongoose is given to each category for fetching there filters

const filterGroupSchema = new Schema({
    name: { type: String, required: true },
    filters: [{
        key: { type: String, required: true }, // e.g., "size"
        label: String, // e.g., "Size"
        ui_type: { type: String, enum: ['button_grid', 'color_swatch', 'checkbox', 'range'] },
        options: [String] // e.g., ["UK 7", "UK 8"]
    }]
}, { timestamps: true });

const FilterGroupModel = model('FilterGroup', filterGroupSchema);
export default FilterGroupModel;
